services:
  postgres:
    image: postgres:17
    container_name: my_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ntkstms_automarket
      POSTGRES_USER: automarket
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in the root .env file}

    ports:
      - "127.0.0.1:5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: