services:
  postgres:
    image: postgres:17
    container_name: my_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ntkstms_automarket
      POSTGRES_USER: automarket
      POSTGRES_PASSWORD: automarket_dev_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: